DROP DATABASE IF EXISTS Lab7;

CREATE DATABASE Lab7;

USE Lab7;

-- Problem 1
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(
  CUST_NUM INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CUST_LNAME VARCHAR(30),
  CUST_FNAME VARCHAR(30),
  CUST_BALANCE DECIMAL(8,2),
  PRIMARY KEY (`CUST_NUM`)
  );
  ALTER TABLE CUSTOMER AUTO_INCREMENT=1000;

-- Problem 2
DROP TABLE IF EXISTS INVOICE;
CREATE TABLE INVOICE(
  INV_NUM INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CUST_NUM INT UNSIGNED NOT NULL,
  INV_DATE DATE,
  INV_AMOUNT DECIMAL(10,2) NULL,
  PRIMARY KEY (`INV_NUM`),
  FOREIGN KEY (`CUST_NUM`) REFERENCES CUSTOMER(`CUST_NUM`)
  );
  ALTER TABLE INVOICE AUTO_INCREMENT=8000;

-- Problem 3
INSERT INTO CUSTOMER (CUST_LNAME, CUST_FNAME, CUST_BALANCE) VALUES ('Smith', 'Jeanne', 1050.11);
INSERT INTO CUSTOMER (CUST_LNAME, CUST_FNAME, CUST_BALANCE) VALUES ('Ortega', 'Juan', 640.92);

-- Problem 4
INSERT INTO INVOICE (CUST_NUM, INV_DATE, INV_AMOUNT) VALUES  (1000, '2016-03-23', 235.89);
INSERT INTO INVOICE (CUST_NUM, INV_DATE, INV_AMOUNT) VALUES  (1001, '2016-03-23', 312.82);
INSERT INTO INVOICE (CUST_NUM, INV_DATE, INV_AMOUNT) VALUES  (1001, '2016-03-30', 528.10);
INSERT INTO INVOICE (CUST_NUM, INV_DATE, INV_AMOUNT) VALUES  (1000, '2016-04-12', 194.78);
INSERT INTO INVOICE (CUST_NUM, INV_DATE, INV_AMOUNT) VALUES  (1000, '2016-04-23', 619.44);

-- Problem 5
 INSERT INTO CUSTOMER (CUST_LNAME, CUST_FNAME, CUST_BALANCE) VALUES ('Powers', 'Ruth', 500);
 
-- Problem 6
ALTER TABLE CUSTOMER
ADD CUST_DOB DATE;
    
-- Problem 7
UPDATE CUSTOMER
SET CUST_DOB = '1989-03-15'
WHERE CUST_NUM = 1000;

-- Problem 8
UPDATE CUSTOMER
SET CUST_DOB = '1988-12-22'
WHERE CUST_NUM = 1001;


-- Problem 9
CREATE TRIGGER trg_updatecustbalance
AFTER INSERT
ON INVOICE
FOR EACH ROW
UPDATE CUSTOMER SET CUST_BALANCE = CUST_BALANCE + NEW.INV_AMOUNT
WHERE CUST_NUM = NEW.CUST_NUM;

INSERT INTO INVOICE (CUST_NUM, INV_DATE, INV_AMOUNT) VALUES (1001, '2018-04-27', 225.40);

-- Problem 10
CREATE PROCEDURE prc_cust_add()
	INSERT INTO CUSTOMER (CUST_LNAME, CUST_FNAME, CUST_BALANCE) VALUES ('Rauthor', 'Peter', 0.00);
CALL prc_cust_add();


-- Problem 11
CREATE PROCEDURE prc_invoice_add()
	INSERT INTO INVOICE (CUST_NUM, INV_DATE, INV_AMOUNT) VALUES (1000, '2018-04-30', 301.72);
CALL prc_invoice_add();

-- Problem 12
CREATE TRIGGER trg_updatecustbalance2
AFTER DELETE
ON INVOICE
FOR EACH ROW
UPDATE CUSTOMER SET CUST_BALANCE = CUST_BALANCE - INV_AMOUNT
WHERE CUSTOMER.CUST_NUM = INVOICE.CUST_NUM;

-- Problem 13
CREATE PROCEDURE prc_inv_delete(INV_NUM INT)
	DELETE FROM INVOICE WHERE INV_NUM = 8005 OR INV_NUM = 8006;
CALL prc_inv_delete(8005);
CALL prc_inv_delete(8006);

	
	


    



  


